### ISSUE TITLE
Store PBKDF2

### ISSUE THREAD

**Issue by hedo95** [leocavalcante/password-dart#2]
Hi,

Using this dart's package, I would like to know how to store the PBKDF2 algorithm because every time I close the app and I have to get back the hash, It gives me another algorithm.

Thanks

**Comment by leocavalcante** [comment]
Hi,

Every time you call `Password.hash` it generates a different hash because of salting, that is part of security. But whenever you call `Password.verify` if this generated hash matches the given plain text, it should properly work.
That is one-way cryptography.

If you are looking for two-way cryptography, like generating always the same encrypted message from the given inputs so you can decrypt this message using the same inputs (key+iv), please, checkout: https://github.com/leocavalcante/encrypt

**Comment by hedo95** [comment]
Great! I like this encrypting way, I use Salsa20, and when I store encrypted.base64, after read this back, Can I get "encrypted" from "encrypted.base64"?

**Comment by hedo95** [comment]
I just saw the method Encrypted.from64(string encrypted), thanks for all ;)
